keymap:
  - key: "t"
    description: "Termianl"
    icon: "/uf1645"
    color: "#222222"
    subKeymap:
      - key: "t"
        description: "Open New Termianl"
        icon: "/uf1645"
        color: "#222222"
        commands:
          - "Exec wt"
      - key: "op"
        description: "Open New PowerShell"
        icon: "/uf1645"
        color: "#222222"
        commands:
          - "Exec wt -p PowerShell"
      - key: "on"
        description: "Open a SSH to Nas"
        icon: "/uf1645"
        color: "#222222"
        commands:
          - "Exec wt -p Nas"
  - key: "e"
    description: "Explorer"
    icon: "/uf1645"
    color: "#222222"
    subKeymap:
      - key: "e"
        description: "Open New Explorer"
        icon: "/uf1645"
        color: "#222222"
        commands:
          - "Exec explorer"
  - key: "f"
    description: "Search and Tools"
    icon: "/uf1645"
    color: "#222222"
    subKeymap:
      - key: "f"
        description: "Open Fluent Search"
        icon: "/uf1645"
        color: "#222222"
        commands: "#f"
      - key: "l"
        description: "Open Listary"
        icon: "/uf1645"
        color: "#222222"
        commands: "^+!f"
      - key: "t"
        description: "Open Pot-Translator"
        icon: "/uf1645"
        color: "#222222"
        commands: "^+!s"
      - key: "e"
        description: "Open Everything"
        icon: "/uf1645"
        color: "#222222"
        commands: "Exec \"C:\\Program Files\\Everything\\Everything.exe\""
  - key: "w"
    description: "Window"
    icon: "/uf1645"
    color: "#222222"
    subKeymap:
      - key: "e"
        description: "set window-edit-mode"
        icon: "/uf1645"
        color: "#222222"
        commands: "Run glazewm command wm-enable-binding-mode --name WINDOW-EDIT-MODE"
      - key: "f"
        description: "set focus-mode"
        icon: "/uf1645"
        color: "#222222"
        commands:
          - "Run glazewm command wm-enable-binding-mode --name FOCUS-MODE"
          - "Run chord_g7.vbs"
